image: node:16

stages:
  - install
  - build
  - deploy

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci

build:
  stage: build
  script:
    - npm run build
    - npm run export
  artifacts:
    paths:
      - out

pages:
  stage: deploy
  script:
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
