image: node:18

stages:
  - install
  - deploy

install:
  stage: install
  script:
    - npm ci

pages:
  stage: deploy
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - out
  cache:
    paths:
      - node_modules
  publish: out
  only:
    - main
